apiVersion: apps/v1
kind: Deployment
metadata:
  name: catsvsdogs-web
  labels:
    app: catsvsdogs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catsvsdogs
  template:
    metadata:
      labels:
        app: catsvsdogs
    spec:
      containers:
        - name: catsvsdogs
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
