apiVersion: v1
kind: Service
metadata:
  name: catsvsdogs-web
  labels:
    app: catsvsdogs
spec:
  type: LoadBalancer
  selector:
    app: catsvsdogs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
